name: cs801-methods
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyterlab
  - ipykernel
  - nbformat
  - nbconvert
  - beautifulsoup4
  - lxml
  - pip
  - pip:
      - wordcloud
